# Generated by Django 5.1.1 on 2024-09-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("patient", "Patient"), ("provider", "Provider")],
                default="patient",
                max_length=10,
            ),
        ),
    ]
