# Generated by Django 5.1.1 on 2024-10-01 20:48


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0005_populate_solana_account_pubkey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="solana_account_pubkey",
            field=models.CharField(
                default="1234", max_length=44, unique=True
            ),
        ),
    ]
