# Generated by Django 5.1.1 on 2024-10-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0007_file_transaction_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="solana_account_pubkey",
            field=models.CharField(blank=True, max_length=44, null=True, unique=True),
        ),
    ]
