# Generated by Django 5.1.1 on 2024-10-08 16:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0008_alter_file_solana_account_pubkey"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="uploaded_at",
            new_name="uploaded_date",
        ),
        migrations.RemoveField(
            model_name="file",
            name="description",
        ),
        migrations.RemoveField(
            model_name="file",
            name="file",
        ),
        migrations.RemoveField(
            model_name="file",
            name="solana_account_pubkey",
        ),
        migrations.RemoveField(
            model_name="file",
            name="uploaded_by",
        ),
        migrations.AddField(
            model_name="file",
            name="shared_with",
            field=models.ManyToManyField(
                related_name="shared_files", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="uploaded_file",
            field=models.FileField(
                default=django.utils.timezone.now, upload_to="user_files/"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="file",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
